exports.Status = {
    NOT_YET_STARTED: 0,
    WORK_IN_PROGRESS: 1,
    COMPLETED: 2,
    YET_TO_RELEASE: 3,
    RELEASED: 4,
    REJECTED: 5,
    RAISING_FUNDS: 6,
    FUNDS_RAISED: 7,
    AUCTION_FOR_INVESTORS: 8,
    AUCTION_FOR_BUILDERS: 9,
    DISCARDED: 10
}